#!/bin/bash
# Detailed explanation of every iptables rule for anonymity

echo "=== DETAILED RULE EXPLANATIONS ==="
echo ""

echo "🔧 BASIC SETUP RULES:"
echo ""

echo "1. RULE: iptables -F"
echo "   WHAT IT DOES: Flushes (deletes) all existing rules"
echo "   WHY NEEDED: Clean slate - removes old conflicting rules"
echo "   EFFECT: No firewall rules exist after this command"
echo ""

echo "2. RULE: iptables -t nat -F"
echo "   WHAT IT DOES: Flushes NAT table rules specifically"
echo "   WHY NEEDED: Clears port forwarding/DNS redirection rules"
echo "   EFFECT: No Network Address Translation rules active"
echo ""

echo "3. RULE: iptables -P INPUT DROP"
echo "   WHAT IT DOES: Sets default policy for INPUT chain to DROP"
echo "   WHY NEEDED: 'Default deny' - block everything unless explicitly allowed"
echo "   EFFECT: All incoming traffic blocked unless a rule allows it"
echo ""

echo "4. RULE: iptables -P OUTPUT DROP"
echo "   WHAT IT DOES: Sets default policy for OUTPUT chain to DROP"
echo "   WHY NEEDED: 'Default deny' for outgoing traffic"
echo "   EFFECT: All outgoing traffic blocked unless a rule allows it"
echo ""

echo "🌐 LOOPBACK & ESTABLISHED:"
echo ""

echo "5. RULE: iptables -A INPUT -i lo -j ACCEPT"
echo "   WHAT IT DOES: Accepts all traffic on loopback interface"
echo "   -i lo: Interface is 'lo' (loopback = 127.0.0.1)"
echo "   -j ACCEPT: Action is to allow the packet"
echo "   WHY NEEDED: System processes need to talk to themselves"
echo "   EXAMPLES: Database connections, X11 display, local services"
echo "   EFFECT: localhost connections work (essential for system to function)"
echo ""

echo "6. RULE: iptables -A OUTPUT -o lo -j ACCEPT"
echo "   WHAT IT DOES: Accepts outgoing traffic on loopback"
echo "   -o lo: Output interface is loopback"
echo "   WHY NEEDED: Complements the INPUT loopback rule"
echo "   EFFECT: Complete two-way localhost communication"
echo ""

echo "7. RULE: iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT"
echo "   WHAT IT DOES: Accepts established connections"
echo "   -m state: Use stateful inspection module"
echo "   --state ESTABLISHED: Connection that already exists"
echo "   --state RELATED: Connection related to existing one"
echo "   WHY NEEDED: Allow responses to your outgoing connections"
echo "   EXAMPLE: If you visit a website, allow the response back"
echo "   EFFECT: Two-way communication works for initiated connections"
echo ""

echo "🏠 LOCAL NETWORK BYPASS:"
echo ""

echo "8. RULE: iptables -t nat -A OUTPUT -d 127.0.0.0/8 -j RETURN"
echo "   WHAT IT DOES: Returns to caller (exits current chain) for localhost"
echo "   -t nat: In NAT table (for packet modification)"
echo "   -d 127.0.0.0/8: Destination is localhost network"
echo "   -j RETURN: Exit chain and continue processing in calling chain"
echo "   WHY NEEDED: Local traffic shouldn't go through Tor"
echo "   EFFECT: localhost traffic bypasses all Tor redirection rules"
echo ""

echo "9. RULE: iptables -t nat -A OUTPUT -d 192.168.0.0/16 -j RETURN"
echo "   WHAT IT DOES: Bypasses Tor for local network traffic"
echo "   -d 192.168.0.0/16: Destination is private network (home/office)"
echo "   WHY NEEDED: You need direct access to local network devices"
echo "   EXAMPLES: Printer at 192.168.1.50, NAS at 192.168.1.100"
echo "   EFFECT: Local network devices accessible directly"
echo ""

echo "10. RULE: iptables -t nat -A OUTPUT -d 10.0.0.0/8 -j RETURN"
echo "    WHAT IT DOES: Bypasses Tor for corporate network"
echo "    -d 10.0.0.0/8: Destination is private corporate network"
echo "    EFFECT: Corporate/intranet resources accessible"
echo ""

echo "11. RULE: iptables -t nat -A OUTPUT -d 172.16.0.0/12 -j RETURN"
echo "    WHAT IT DOES: Bypasses Tor for another private network range"
echo "    -d 172.16.0.0/12: Docker/VM private networks often use this"
echo "    EFFECT: Docker containers, VMs accessible"
echo ""

echo "🧅 TOR USER ALLOWANCE:"
echo ""

echo "12. RULE: iptables -t nat -A OUTPUT -m owner --uid-owner debian-tor -j RETURN"
echo "    WHAT IT DOES: Allows Tor process to bypass its own redirection"
echo "    -m owner: Match based on process owner"
echo "    --uid-owner debian-tor: Process owned by 'debian-tor' user"
echo "    WHY NEEDED: Tor needs to access internet directly (not through itself!)"
echo "    EFFECT: Tor can connect to the network to establish circuits"
echo ""

echo "🔍 DNS LEAK PREVENTION:"
echo ""

echo "13. RULE: iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 53"
echo "    WHAT IT DOES: Redirects all DNS queries to local DNS resolver"
echo "    -p udp: Protocol is UDP (most DNS is UDP)"
echo "    --dport 53: Destination port is 53 (DNS port)"
echo "    -j REDIRECT: Action is redirect to localhost"
echo "    --to-ports 53: Redirect to port 53 on this machine"
echo "    WHAT HAPPENS:"
echo "    Your app tries to resolve google.com → Asks 8.8.8.8:53"
echo "    iptables intercepts → Redirects to 127.0.0.1:53"
echo "    Tor's DNS resolver answers → Goes through Tor anonymously"
echo "    WHY NEEDED: Prevents DNS leaks that reveal your IP"
echo ""

echo "14. RULE: iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports 53"
echo "    WHAT IT DOES: Same as above but for TCP DNS queries"
echo "    -p tcp: Protocol is TCP (some DNS over TCP)"
echo "    WHY NEEDED: Some systems use TCP for DNS queries"
echo "    EFFECT: Complete DNS leak protection"
echo ""

echo "🌊 TRAFFIC FORCING:"
echo ""

echo "15. RULE: iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports 9040"
echo "    WHAT IT DOES: Forces all new TCP connections through Tor"
echo "    -p tcp: Protocol is TCP"
echo "    --syn: Only new connections (SYN flag set)"
echo "    -j REDIRECT --to-ports 9040: Redirect to Tor's SOCKS port"
echo "    WHAT HAPPENS:"
echo "    You try to visit example.com:80"
echo "    iptables intercepts: 'New TCP connection! Redirect to port 9040'"
echo "    Tor receives connection → Routes through Tor network"
echo "    Target website sees Tor exit node IP, not yours"
echo "    WHY NEEDED: Prevents direct internet connections"
echo ""

echo "🚪 DIRECT TOR ACCESS:"
echo ""

echo "16. RULE: iptables -A OUTPUT -p tcp --dport 9040 -j ACCEPT"
echo "    WHAT IT DOES: Allows connections to Tor's SOCKS port"
echo "    -p tcp --dport 9040: Destination is Tor's SOCKS port"
echo "    WHY NEEDED: Applications need to connect to Tor directly"
echo "    EFFECT: Tor-aware applications work correctly"
echo ""

echo "17. RULE: iptables -A OUTPUT -p tcp --dport 9050 -j ACCEPT"
echo "    WHAT IT DOES: Allows connections to Tor's control port"
echo "    -p tcp --dport 9050: Destination is Tor's control port"
echo "    WHY NEEDED: Some applications use Tor's control protocol"
echo "    EFFECT: Full Tor functionality available"
echo ""

echo "🚫 FINAL BLOCKING:"
echo ""

echo "18. RULE: iptables -A OUTPUT -j REJECT --reject-with icmp-port-unreachable"
echo "    WHAT IT DOES: Blocks all remaining outgoing traffic"
echo "    -j REJECT: Actively reject with error message"
echo "    --reject-with icmp-port-unreachable: Send 'port closed' error"
echo "    WHY NEEDED: Catch-all for anything that slipped through"
echo "    EFFECT: Absolute guarantee that all traffic goes through Tor"
echo ""

echo "=== SUMMARY OF TRAFFIC FLOW ==="
echo ""
echo "📊 TRAFFIC DECISION TREE:"
echo "1. Is it localhost traffic? → Allow (rules 5,6)"
echo "2. Is it an established connection? → Allow (rule 7)"
echo "3. Is it local network traffic? → Bypass Tor (rules 8-11)"
echo "4. Is it from Tor user? → Allow direct access (rule 12)"
echo "5. Is it a DNS query? → Redirect through Tor (rules 13,14)"
echo "6. Is it a new TCP connection? → Redirect through Tor (rule 15)"
echo "7. Is it to Tor's own ports? → Allow (rules 16,17)"
echo "8. Anything else? → BLOCK (rule 18)"
echo ""
echo "🎯 RESULT: Your real IP is never exposed to the internet!"