#!/bin/bash
#===============================================================================
#
#          FILE:  automation_manager.sh
#
#         USAGE:  auto_doc <function_name> [output_file]
#                 auto_scaffold <project_type> <name> [destination]
#                 auto_generate <template> <name> [destination]
#                 auto_help
#
#   DESCRIPTION:  Automation system for documentation generation,
#                 project scaffolding, and template management
#
#       OPTIONS:  function_name - Function to document
#                 project_type - Type of project to scaffold
#                 template - Template to use
#                 name - Name of project/template
#                 destination - Where to create
#  REQUIREMENTS:  jq, sed, grep
#         NOTES:  Generates documentation and project structures
#        AUTHOR:  bash.d project
#       VERSION:  1.0.0
#===============================================================================

# Configuration
AUTO_TEMPLATES_DIR="${HOME}/.config/bashd/automation/templates"
AUTO_DOCS_DIR="${HOME}/.config/bashd/automation/docs"
mkdir -p "$AUTO_TEMPLATES_DIR" "$AUTO_DOCS_DIR"

# Automatically document a function
auto_doc() {
    local func_name="${1}"
    local output_file="${2:-${AUTO_DOCS_DIR}/${func_name}.md}"

    if [[ -z "$func_name" ]]; then
        echo "Usage: auto_doc <function_name> [output_file]"
        return 1
    fi

    # Find the function file
    local repo_dir="${BASH_D_REPO:-$HOME/bash.d}"
    local functions_dir="${repo_dir}/bash_functions.d"
    local found_file

    found_file=$(find "$functions_dir" -name "${func_name}.sh" -type f 2>/dev/null | head -1)

    if [[ -z "$found_file" ]]; then
        echo "Function not found: $func_name"
        return 1
    fi

    echo "Generating documentation for: $func_name"
    echo "Output: $output_file"

    # Extract function information
    local func_signature
    func_signature=$(grep -E "^${func_name}\(\)" "$found_file" | head -1)

    local func_description
    func_description=$(sed -n '/#.*DESCRIPTION/,/#.*[A-Z]\{4,\}/p' "$found_file" | head -5 | sed 's/^# *//' | sed 's/^ *//')

    local func_usage
    func_usage=$(sed -n '/#.*USAGE/,/#.*[A-Z]\{4,\}/p' "$found_file" | head -5 | sed 's/^# *//' | sed 's/^ *//')

    local func_options
    func_options=$(sed -n '/#.*OPTIONS/,/#.*[A-Z]\{4,\}/p' "$found_file" | head -10 | sed 's/^# *//' | sed 's/^ *//')

    local func_requirements
    func_requirements=$(sed -n '/#.*REQUIREMENTS/,/#.*[A-Z]\{4,\}/p' "$found_file" | head -5 | sed 's/^# *//' | sed 's/^ *//')

    local func_notes
    func_notes=$(sed -n '/#.*NOTES/,/#.*[A-Z]\{4,\}/p' "$found_file" | head -5 | sed 's/^# *//' | sed 's/^ *//')

    # Generate markdown documentation
    cat > "$output_file" << EOF
# ${func_name}

## Function Signature
\`\`\`bash
${func_signature}
\`\`\`

## Description
${func_description}

## Usage
${func_usage}

## Options
${func_options}

## Requirements
${func_requirements}

## Notes
${func_notes}

## Source Code
\`\`\`bash
$(cat "$found_file")
\`\`\`

## Generated
Generated by auto_doc on $(date -u +'%Y-%m-%dT%H:%M:%SZ')
EOF

    echo "✓ Documentation generated: $output_file"
}

# Automatically scaffold a project
auto_scaffold() {
    local project_type="${1}"
    local name="${2}"
    local destination="${3:-./$name}"

    if [[ -z "$project_type" || -z "$name" ]]; then
        echo "Usage: auto_scaffold <project_type> <name> [destination]"
        echo ""
        echo "Project Types:"
        echo "  bash       - Bash project"
        echo "  python     - Python project"
        echo "  node       - Node.js project"
        echo "  web        - Web project"
        echo "  docs       - Documentation project"
        echo "  generic    - Generic project"
        return 1
    fi

    echo "Scaffolding $project_type project: $name"
    echo "Destination: $destination"

    # Create destination directory
    mkdir -p "$destination"

    case "$project_type" in
        bash)
            _scaffold_bash "$name" "$destination"
            ;;
        python)
            _scaffold_python "$name" "$destination"
            ;;
        node)
            _scaffold_node "$name" "$destination"
            ;;
        web)
            _scaffold_web "$name" "$destination"
            ;;
        docs)
            _scaffold_docs "$name" "$destination"
            ;;
        generic|*)
            _scaffold_generic "$name" "$destination"
            ;;
    esac

    echo "✓ Project scaffolded: $destination"
}

# Scaffold bash project
_scaffold_bash() {
    local name="${1}"
    local destination="${2}"

    # Create basic structure
    mkdir -p "$destination/src" "$destination/tests" "$destination/docs"

    # Create README
    cat > "$destination/README.md" << EOF
# ${name}

## Description
Bash project scaffolded with auto_scaffold

## Features
- Modular bash scripts
- Testing framework
- Documentation

## Usage
\`\`\`bash
source src/main.sh
\`\`\`

## Structure
- src/ - Source code
- tests/ - Test scripts
- docs/ - Documentation
EOF

    # Create main script
    cat > "$destination/src/main.sh" << 'EOF'
#!/bin/bash
# Main script for the project

main() {
    echo "Hello from ${name}!"
    echo "Project created with auto_scaffold"
}

main "$@"
EOF

    chmod +x "$destination/src/main.sh"

    # Create test script
    cat > "$destination/tests/test_main.sh" << 'EOF'
#!/bin/bash
# Test script for main functionality

test_main() {
    echo "Testing main functionality..."
    # Add your tests here
    echo "Tests completed"
}

test_main
EOF

    chmod +x "$destination/tests/test_main.sh"

    # Create documentation
    cat > "$destination/docs/overview.md" << EOF
# Project Overview

## Purpose
This project was created to demonstrate bash scaffolding.

## Components
- Main script: src/main.sh
- Test suite: tests/test_main.sh
- Documentation: docs/

## Getting Started
1. Source the main script: source src/main.sh
2. Run tests: ./tests/test_main.sh
EOF
}

# Scaffold Python project
_scaffold_python() {
    local name="${1}"
    local destination="${2}"

    # Create basic structure
    mkdir -p "$destination/src" "$destination/tests" "$destination/docs" "$destination/scripts"

    # Create README
    cat > "$destination/README.md" << EOF
# ${name}

## Description
Python project scaffolded with auto_scaffold

## Features
- Modular Python code
- Testing with pytest
- Documentation

## Usage
\`\`\`bash
python -m src.main
\`\`\`

## Structure
- src/ - Source code
- tests/ - Test scripts
- docs/ - Documentation
- scripts/ - Utility scripts
EOF

    # Create main Python file
    cat > "$destination/src/main.py" << EOF
#!/usr/bin/env python3
\"\"\"Main module for ${name} project.\"\"\"

def main():
    \"\"\"Main entry point.\"\"\"
    print(f\"Hello from {name}!\")
    print(\"Project created with auto_scaffold\")

if __name__ == \"__main__\":
    main()
EOF

    # Create test file
    cat > "$destination/tests/test_main.py" << EOF
#!/usr/bin/env python3
\"\"\"Tests for main module.\"\"\"

import pytest
from src.main import main

def test_main():
    \"\"\"Test main function.\"\"\"
    # Add your tests here
    assert True
EOF

    # Create requirements file
    cat > "$destination/requirements.txt" << EOF
# Project dependencies
pytest>=7.0.0
EOF

    # Create documentation
    cat > "$destination/docs/overview.md" << EOF
# Project Overview

## Purpose
This project was created to demonstrate Python scaffolding.

## Components
- Main module: src/main.py
- Test suite: tests/test_main.py
- Documentation: docs/

## Getting Started
1. Install dependencies: pip install -r requirements.txt
2. Run main module: python -m src.main
3. Run tests: pytest
EOF
}

# Scaffold Node.js project
_scaffold_node() {
    local name="${1}"
    local destination="${2}"

    # Create basic structure
    mkdir -p "$destination/src" "$destination/tests" "$destination/docs" "$destination/scripts"

    # Create package.json
    cat > "$destination/package.json" << EOF
{
  "name": "${name}",
  "version": "1.0.0",
  "description": "Node.js project scaffolded with auto_scaffold",
  "main": "src/index.js",
  "scripts": {
    "start": "node src/index.js",
    "test": "jest",
    "lint": "eslint src/"
  },
  "dependencies": {
    "express": "^4.18.0"
  },
  "devDependencies": {
    "jest": "^29.0.0",
    "eslint": "^8.0.0"
  }
}
EOF

    # Create README
    cat > "$destination/README.md" << EOF
# ${name}

## Description
Node.js project scaffolded with auto_scaffold

## Features
- Express.js web server
- Jest testing
- ESLint linting

## Usage
\`\`\`bash
npm install
npm start
\`\`\`

## Structure
- src/ - Source code
- tests/ - Test scripts
- docs/ - Documentation
- scripts/ - Utility scripts
EOF

    # Create main JavaScript file
    cat > "$destination/src/index.js" << EOF
/**
 * Main module for ${name} project
 */

const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

app.get('/', (req, res) => {
    res.send('Hello from ${name}! Project created with auto_scaffold');
});

app.listen(PORT, () => {
    console.log(\`Server running on port \${PORT}\`);
});
EOF

    # Create test file
    cat > "$destination/tests/index.test.js" << EOF
/**
 * Tests for main module
 */

const request = require('supertest');
const app = require('../src/index');

describe('GET /', () => {
    it('should respond with hello message', async () => {
        const response = await request(app).get('/');
        expect(response.statusCode).toBe(200);
        expect(response.text).toContain('Hello from ${name}');
    });
});
EOF

    # Create documentation
    cat > "$destination/docs/overview.md" << EOF
# Project Overview

## Purpose
This project was created to demonstrate Node.js scaffolding.

## Components
- Main module: src/index.js
- Test suite: tests/index.test.js
- Documentation: docs/

## Getting Started
1. Install dependencies: npm install
2. Start server: npm start
3. Run tests: npm test
EOF
}

# Scaffold web project
_scaffold_web() {
    local name="${1}"
    local destination="${2}"

    # Create basic structure
    mkdir -p "$destination/src" "$destination/public" "$destination/public/css" "$destination/public/js" "$destination/public/img" "$destination/docs"

    # Create index.html
    cat > "$destination/public/index.html" << EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${name}</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <h1>${name}</h1>
        <p>Web project created with auto_scaffold</p>
    </header>
    <main>
        <section id="content">
            <p>Welcome to the ${name} project!</p>
        </section>
    </main>
    <footer>
        <p>&copy; $(date +%Y) ${name}</p>
    </footer>
    <script src="js/main.js"></script>
</body>
</html>
EOF

    # Create CSS file
    cat > "$destination/public/css/style.css" << EOF
/* Main styles for ${name} project */

body {
    font-family: Arial, sans-serif;
    line-height: 1.6;
    margin: 0;
    padding: 0;
    color: #333;
}

header {
    background-color: #007bff;
    color: white;
    padding: 1rem;
    text-align: center;
}

main {
    padding: 2rem;
    max-width: 1200px;
    margin: 0 auto;
}

footer {
    background-color: #f8f9fa;
    padding: 1rem;
    text-align: center;
    margin-top: 2rem;
}
EOF

    # Create JavaScript file
    cat > "$destination/public/js/main.js" << EOF
/**
 * Main JavaScript for ${name} project
 */

document.addEventListener('DOMContentLoaded', function() {
    console.log('${name} project loaded');
    // Add your JavaScript here
});
EOF

    # Create README
    cat > "$destination/README.md" << EOF
# ${name}

## Description
Web project scaffolded with auto_scaffold

## Features
- HTML5 structure
- CSS styling
- JavaScript functionality

## Usage
Open index.html in a web browser

## Structure
- public/ - Static files
  - css/ - Stylesheets
  - js/ - JavaScript
  - img/ - Images
- docs/ - Documentation
EOF

    # Create documentation
    cat > "$destination/docs/overview.md" << EOF
# Project Overview

## Purpose
This project was created to demonstrate web scaffolding.

## Components
- HTML: public/index.html
- CSS: public/css/style.css
- JavaScript: public/js/main.js
- Documentation: docs/

## Getting Started
1. Open index.html in a web browser
2. Customize the HTML, CSS, and JavaScript files
EOF
}

# Scaffold generic project
_scaffold_generic() {
    local name="${1}"
    local destination="${2}"

    # Create basic structure
    mkdir -p "$destination" "$destination/docs"

    # Create README
    cat > "$destination/README.md" << EOF
# ${name}

## Description
Generic project scaffolded with auto_scaffold

## Features
- Basic project structure
- Documentation

## Usage
Customize this project for your needs

## Structure
- docs/ - Documentation
EOF

    # Create documentation
    cat > "$destination/docs/overview.md" << EOF
# Project Overview

## Purpose
This project was created to demonstrate generic scaffolding.

## Components
- README: README.md
- Documentation: docs/

## Getting Started
1. Customize the README.md file
2. Add your project files
3. Update documentation
EOF
}

# Generate from template
auto_generate() {
    local template="${1}"
    local name="${2}"
    local destination="${3:-./$name}"

    if [[ -z "$template" || -z "$name" ]]; then
        echo "Usage: auto_generate <template> <name> [destination]"
        echo ""
        echo "Available Templates:"
        ls "$AUTO_TEMPLATES_DIR" 2>/dev/null | sed 's/\.sh$//'
        return 1
    fi

    local template_file="${AUTO_TEMPLATES_DIR}/${template}.sh"

    if [[ ! -f "$template_file" ]]; then
        echo "Template not found: $template"
        return 1
    fi

    echo "Generating from template: $template"
    echo "Name: $name"
    echo "Destination: $destination"

    # Create destination directory
    mkdir -p "$destination"

    # Execute the template script
    if [[ -x "$template_file" ]]; then
        "$template_file" "$name" "$destination"
    else
        echo "Template is not executable: $template_file"
        return 1
    fi

    echo "✓ Generated from template: $template"
}

# Create a new template
auto_template_create() {
    local name="${1}"

    if [[ -z "$name" ]]; then
        echo "Usage: auto_template_create <name>"
        return 1
    fi

    local template_file="${AUTO_TEMPLATES_DIR}/${name}.sh"

    if [[ -f "$template_file" ]]; then
        echo "Template already exists: $name"
        return 1
    fi

    # Create template file
    cat > "$template_file" << 'EOF'
#!/bin/bash
# Template: TEMPLATE_NAME

template_main() {
    local name="${1}"
    local destination="${2}"

    echo "Template: $name"
    echo "Destination: $destination"

    # Add your template logic here
    mkdir -p "$destination"
    echo "Template executed for: $name" > "$destination/README.md"
}

# Execute template
template_main "$@"
EOF

    chmod +x "$template_file"
    echo "✓ Created template: $name"
    echo "Edit the template file: $template_file"
}

# List available templates
auto_template_list() {
    echo "Available Templates:"
    echo "════════════════════════════════════════════════════════════════"

    if [[ -d "$AUTO_TEMPLATES_DIR" ]]; then
        for template_file in "$AUTO_TEMPLATES_DIR"/*.sh; do
            if [[ -f "$template_file" ]]; then
                local name
                name=$(basename "$template_file" .sh)
                echo "  $name"
            fi
        done
    else
        echo "No templates found"
    fi
}

# Automation help
auto_help() {
    cat << 'EOF'
Automation Commands:

  auto_doc <function> [output]      - Generate function documentation
  auto_scaffold <type> <name> [dest] - Scaffold a new project
  auto_generate <template> <name> [dest] - Generate from template
  auto_template_create <name>      - Create a new template
  auto_template_list               - List available templates
  auto_help                        - Show this help message

Project Types:
  bash       - Bash project
  python     - Python project
  node       - Node.js project
  web        - Web project
  docs       - Documentation project
  generic    - Generic project

Examples:
  auto_doc func_recall
  auto_scaffold python my_project
  auto_generate bash_template my_script
  auto_template_create python_template
  auto_template_list
EOF
}

# Export functions
export -f auto_doc 2>/dev/null
export -f auto_scaffold 2>/dev/null
export -f _scaffold_bash 2>/dev/null
export -f _scaffold_python 2>/dev/null
export -f _scaffold_node 2>/dev/null
export -f _scaffold_web 2>/dev/null
export -f _scaffold_generic 2>/dev/null
export -f auto_generate 2>/dev/null
export -f auto_template_create 2>/dev/null
export -f auto_template_list 2>/dev/null
export -f auto_help 2>/dev/null
